Migrate S3 bucket to ARD WG account
cloudfoundry/cf-smoke-tests-release pull request #24
Opened 2023-11-21 09:29 UTC by jochenehret

2023-11-21 18:18 UTC, ctlong requested changes
Could we move the blobs to a new cloud storage bucket in our GCP project instead? That's where we currently store all of our blobs, and it would be nice to keep them centralized.

2023-11-22 07:00 UTC, jochenehret commented
Ok, we can also use GCS. I'll create a new bucket for this BOSH release.

2023-11-24 10:05 UTC, iaftab-alam approved these changes

2023-11-27 17:10 UTC, ctlong approved these changes

2023-11-28 08:38 UTC, merged